config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stocks
  resources :portfolios do
    resources :positions
  end

  root to: "portfolios#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  
  belongs_to :user

  has_many :positions, dependent: :destroy

  def size
    portsize = 0
    positions.each do |position|
      portsize += position.position_size
    end
    portsize
  end

  def stocklist
    stocklist = []
    positions.each do |stock|
      stocklist << Stock.find_by(id: stock.stock_id).symbol
    end
    stocklist.uniq
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :portfolio
  belongs_to :stock

  monetize :cost_cents, as: "cost"

  def position_size
    cost * quantity
  end

  def portfolio_part
    ((position_size / portfolio.size) * 100).round(2)
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :positions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :confirmable

  has_many :portfolios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :user_id)
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :get_portfolio
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = @portfolio.positions
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = @portfolio.positions.build
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = @portfolio.positions.build(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to portfolio_positions_path(@portfolio), notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to portfolio_position_path(@portfolio), notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_positions_path(@portfolio), notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_portfolio
      @portfolio = Portfolio.find(params[:portfolio_id])
    end

    def set_position
      @position = @portfolio.positions.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:open_date, :close_date, :cost_cents, :quantity, :notes, :status, :portfolio_id, :stock_id)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:name, :symbol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stonks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
        <% portfolio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Stocks</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.name %></td>
        <td><%= portfolio.user_id %></td>
        <td><%= portfolio.stocklist.count %></td>
        <td><%= humanized_money_with_symbol portfolio.size %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @portfolio.name
p#notice
  = notice
h1
  | Stocks
table
  thead
    tr
      th
        | Symbol
  tbody
    - @portfolio.stocklist.each do |symbol|
      tr
        td
          = symbol
h1
  | Positions
table
  thead
    tr
      th
        | Stock
      th
        | Cost
      th
        | Quantity
      th
        | Position Size
      th
        | Portfolio %
      th
        | Notes
      th
        | Status
      th
        | Portfolio
      th
        | Open date
      th
        | Close date
      th
        | Days Holding Stock
      th[colspan="2"]
  tbody
    - @portfolio.positions.each do |position|
      tr
        td
          = Stock.find_by(id: position.stock_id).symbol
        td
          = humanized_money_with_symbol position.cost
        td
          = position.quantity
        td
          = humanized_money_with_symbol position.position_size
        td
          = position.portfolio_part
        td
          = position.notes
        td
          = position.status
        td
          = position.portfolio_id
        td
          = position.open_date
        td
          = position.close_date
        td
          = distance_of_time_in_words(position.open_date, position.close_date)
        td
          = link_to 'Edit Position', edit_portfolio_position_path(@portfolio, position)
        td
          = link_to 'Destroy Position', [@portfolio, position], method: :delete, data: { confirm: 'Are you sure?' }
br
h3
  | Add a New Position
= link_to 'New Position', new_portfolio_position_path(@portfolio)
h4
  | Tata for now

app/views/positions/_form.html.erb
<%= form_with(model: [@portfolio, position], local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :open_date %>
    <%= form.date_select :open_date %>
  </div>

  <div class="field">
    <%= form.label :close_date %>
    <%= form.date_select :close_date %>
  </div>

  <div class="field">
    <%= form.label :cost_cents %>
    <%= form.number_field :cost_cents %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :stock_id %>
    <%= form.text_field :stock_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', [@portfolio, @position] %> |
<%= link_to 'Back', portfolio_path(@portfolio) %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
    </tr>
  </thead>
  <tbody>
    <%= stocklist %>
  </tbody>
</table>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Open date</th>
      <th>Close date</th>
      <th>Cost</th>
      <th>Quantity</th>
      <th>Position Size</th>
      <th>Portfolio %</th>
      <th>Notes</th>
      <th>Status</th>
      <th>Portfolio</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.open_date %></td>
        <td><%= position.close_date %></td>
        <td><%= humanized_money_with_symbol position.cost %></td>
        <td><%= position.quantity %></td>
        <td><%= humanized_money_with_symbol position.position_size %></td>
        <td><%= position.portfolio_part %></td>
        <td><%= position.notes %></td>
        <td><%= position.status %></td>
        <td><%= position.portfolio_id %></td>
        <td><%= Stock.find_by(id: position.stock_id).symbol %></td>
        <td><%= link_to 'Show Portfolio', [@portfolio] %></td>
        <td><%= link_to 'Edit Position', edit_portfolio_position_path(@portfolio, position) %></td>
        <td><%= link_to 'Destroy Position', [@portfolio, position], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3>Add a New Position</h3>
<%= render 'form', position: @portfolio.positions.build %>

<%= link_to 'Open Position', new_portfolio_position_path(@portfolio) %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', portfolio_positions_path(@portfolio) %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Open date:</strong>
  <%= @position.open_date %>
</p>

<p>
  <strong>Close date:</strong>
  <%= @position.close_date %>
</p>

<p>
  <strong>Cost:</strong>
  <%= humanized_money_with_symbol @position.cost %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @position.quantity %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @position.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @position.status %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @position.portfolio_id %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @position.stock_id %>
</p>

<%= link_to 'Edit', edit_portfolio_position_path(@portfolio, @position) %> |
<%= link_to 'Back', portfolio_positions_path(@portfolio) %>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.symbol %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @stock.symbol %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>